apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base # Reference to the base manifest directory

images:
# This image block is updated by Cloud Build with the new tag
- name: app-image
  newName: us-central1-docker.pkg.dev/YOUR_PROJECT_ID/microservice-repo/app
  newTag: initial-tag
